version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 54123638 # 设置数据库 root 密码
      MYSQL_DATABASE: shopping_site # 自动创建的数据库名称
      MYSQL_USER: shop_user # 数据库用户
      MYSQL_PASSWORD: shop_password # 用户密码
    ports:
      - "3306:3306" # 将容器的3306端口映射到主机的3306端口
    volumes:
      - db_data:/var/lib/mysql # 持久化存储
    networks:
      - shopesay-network

volumes:
  db_data:

networks:
  shopesay-network: